name: Publish

on:
  push:
    tags: 
    - 'v*'

jobs:
  test:
    uses: ./.github/workflows/test.yml
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - run: npm run build
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/static/css/*.css,build/static/js/*.js"
          token: ${{ secrets.GITHUB_TOKEN }}